export const LAUNDRY_PACKAGE_ACTION_TYPES = {
    FETCH_LAUNDRY_PACKAGES_START: 'laundry_package/FETCH_LAUNDRY_PACKAGES_START',
    FETCH_LAUNDRY_PACKAGES_SUCCESS: 'laundry_package/FETCH_LAUNDRY_PACKAGES_SUCCESS',
    FETCH_LAUNDRY_PACKAGES_FAILED: 'laundry_package/FETCH_LAUNDRY_PACKAGES_FAILED',
}