export const EMPLOYEE_ACTION_TYPES = {
    FETCH_EMPLOYEES_START: 'employee/FETCH_EMPLOYEES_START',
    FETCH_EMPLOYEES_SUCCESS: 'employee/FETCH_EMPLOYEES_SUCCESS',
    FETCH_EMPLOYEES_FAILED: 'employee/FETCH_EMPLOYEES_FAILED',
}