export const COMPANY_PROFILE_ACTION_TYPES = {
    FETCH_COMPANY_PROFILE_START: 'user/FETCH_COMPANY_PROFILE_START',
    FETCH_COMPANY_PROFILE_SUCCESS: 'user/FETCH_COMPANY_PROFILE_SUCCESS',
    FETCH_COMPANY_PROFILE_FAILED: 'user/FETCH_COMPANY_PROFILE_FAILED',
}