export const CUSTOMER_ACTION_TYPES = {
    FETCH_CUSTOMERS_START: 'customer/FETCH_CUSTOMERS_START',
    FETCH_CUSTOMERS_SUCCESS: 'customer/FETCH_CUSTOMERS_SUCCESS',
    FETCH_CUSTOMERS_FAILED: 'customer/FETCH_CUSTOMERS_FAILED',
}