export const SUMMARY_ACTION_TYPES = {
    FETCH_SUMMARY_START: 'summary/FETCH_SUMMARY_START',
    FETCH_SUMMARY_SUCCESS: 'summary/FETCH_SUMMARY_SUCCESS',
    FETCH_SUMMARY_FAILED: 'summary/FETCH_SUMMARY_FAILED',
}

export const DAILY_TRANSACTION_TOTAL_ACTION_TYPES = {
    FETCH_DAILY_TRANSACTION_TOTAL_START: 'summary/FETCH_DAILY_TRANSACTION_TOTAL_START',
    FETCH_DAILY_TRANSACTION_TOTAL_SUCCESS: 'summary/FETCH_DAILY_TRANSACTION_TOTAL_SUCCESS',
    FETCH_DAILY_TRANSACTION_TOTAL_FAILED: 'summary/FETCH_DAILY_TRANSACTION_TOTAL_FAILED',
}