export const PAYMENT_TYPE_ACTION_TYPES = {
    FETCH_PAYMENT_TYPES_START: 'payment_type/FETCH_PAYMENT_TYPES_START',
    FETCH_PAYMENT_TYPES_SUCCESS: 'payment_type/FETCH_PAYMENT_TYPES_SUCCESS',
    FETCH_PAYMENT_TYPES_FAILED: 'payment_type/FETCH_PAYMENT_TYPES_FAILED',
}