export const SALES_ACTION_TYPES = {
    FETCH_SALES_START: 'sales/FETCH_SALES_START',
    FETCH_SALES_SUCCESS: 'sales/FETCH_SALES_SUCCESS',
    FETCH_SALES_FAILED: 'sales/FETCH_SALES_FAILED',
}

export const UNPROCESSED_SALES_ACTION_TYPES = {
    FETCH_UNPROCESSED_SALES_START: 'sales/FETCH_UNPROCESSED_SALES_START',
    FETCH_UNPROCESSED_SALES_SUCCESS: 'sales/FETCH_UNPROCESSED_SALES_SUCCESS',
    FETCH_UNPROCESSED_SALES_FAILED: 'sales/FETCH_UNPROCESSED_SALES_FAILED',
}