export const ACTION_TYPE = {
    SET_LOGGED_IN_PROFILE: "SET_LOGGED_IN_PROFILE",
    SET_COMPANY_PROFILE: "SET_COMPANY_PROFILE",
    SET_LOGGED_IN_FULLNAME: "SET_LOGGED_IN_FULLNAME",
    SET_TOGGLE_SIDEBAR_MENU: "SET_TOGGLE_SIDEBAR_MENU",
};

export const TOAST_TYPE = {
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR', 
};
